/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewWorkbenchRouteImport } from './routes/review-workbench'
import { Route as ReviewConsoleRouteImport } from './routes/review-console'
import { Route as PortalTrustRouteImport } from './routes/portal-trust'
import { Route as PortalOperationsRouteImport } from './routes/portal-operations'
import { Route as IndexRouteImport } from './routes/index'

const ReviewWorkbenchRoute = ReviewWorkbenchRouteImport.update({
  id: '/review-workbench',
  path: '/review-workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewConsoleRoute = ReviewConsoleRouteImport.update({
  id: '/review-console',
  path: '/review-console',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTrustRoute = PortalTrustRouteImport.update({
  id: '/portal-trust',
  path: '/portal-trust',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOperationsRoute = PortalOperationsRouteImport.update({
  id: '/portal-operations',
  path: '/portal-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal-operations': typeof PortalOperationsRoute
  '/portal-trust': typeof PortalTrustRoute
  '/review-console': typeof ReviewConsoleRoute
  '/review-workbench': typeof ReviewWorkbenchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portal-operations': typeof PortalOperationsRoute
  '/portal-trust': typeof PortalTrustRoute
  '/review-console': typeof ReviewConsoleRoute
  '/review-workbench': typeof ReviewWorkbenchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal-operations': typeof PortalOperationsRoute
  '/portal-trust': typeof PortalTrustRoute
  '/review-console': typeof ReviewConsoleRoute
  '/review-workbench': typeof ReviewWorkbenchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal-operations'
    | '/portal-trust'
    | '/review-console'
    | '/review-workbench'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/portal-operations'
    | '/portal-trust'
    | '/review-console'
    | '/review-workbench'
  id:
    | '__root__'
    | '/'
    | '/portal-operations'
    | '/portal-trust'
    | '/review-console'
    | '/review-workbench'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalOperationsRoute: typeof PortalOperationsRoute
  PortalTrustRoute: typeof PortalTrustRoute
  ReviewConsoleRoute: typeof ReviewConsoleRoute
  ReviewWorkbenchRoute: typeof ReviewWorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-workbench': {
      id: '/review-workbench'
      path: '/review-workbench'
      fullPath: '/review-workbench'
      preLoaderRoute: typeof ReviewWorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review-console': {
      id: '/review-console'
      path: '/review-console'
      fullPath: '/review-console'
      preLoaderRoute: typeof ReviewConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-trust': {
      id: '/portal-trust'
      path: '/portal-trust'
      fullPath: '/portal-trust'
      preLoaderRoute: typeof PortalTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-operations': {
      id: '/portal-operations'
      path: '/portal-operations'
      fullPath: '/portal-operations'
      preLoaderRoute: typeof PortalOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalOperationsRoute: PortalOperationsRoute,
  PortalTrustRoute: PortalTrustRoute,
  ReviewConsoleRoute: ReviewConsoleRoute,
  ReviewWorkbenchRoute: ReviewWorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
