/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationsRouteImport } from './routes/verifications'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ApiDocupipeWebhookRouteImport } from './routes/api/docupipe/webhook'

const VerificationsRoute = VerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocupipeWebhookRoute = ApiDocupipeWebhookRouteImport.update({
  id: '/api/docupipe/webhook',
  path: '/api/docupipe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/upload': typeof UploadRoute
  '/verifications': typeof VerificationsRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/docupipe/webhook': typeof ApiDocupipeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/upload': typeof UploadRoute
  '/verifications': typeof VerificationsRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/docupipe/webhook': typeof ApiDocupipeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/processing': typeof ProcessingRoute
  '/upload': typeof UploadRoute
  '/verifications': typeof VerificationsRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/api/docupipe/webhook': typeof ApiDocupipeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/confirmation'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/upload'
    | '/verifications'
    | '/api/uploads'
    | '/api/docupipe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/confirmation'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/upload'
    | '/verifications'
    | '/api/uploads'
    | '/api/docupipe/webhook'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/confirmation'
    | '/dashboard'
    | '/login'
    | '/processing'
    | '/upload'
    | '/verifications'
    | '/api/uploads'
    | '/api/docupipe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProcessingRoute: typeof ProcessingRoute
  UploadRoute: typeof UploadRoute
  VerificationsRoute: typeof VerificationsRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  ApiDocupipeWebhookRoute: typeof ApiDocupipeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifications': {
      id: '/verifications'
      path: '/verifications'
      fullPath: '/verifications'
      preLoaderRoute: typeof VerificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docupipe/webhook': {
      id: '/api/docupipe/webhook'
      path: '/api/docupipe/webhook'
      fullPath: '/api/docupipe/webhook'
      preLoaderRoute: typeof ApiDocupipeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProcessingRoute: ProcessingRoute,
  UploadRoute: UploadRoute,
  VerificationsRoute: VerificationsRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  ApiDocupipeWebhookRoute: ApiDocupipeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
